/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiAiContextRouteImport } from './routes/api/ai/context'
import { Route as ApiAiAskRouteImport } from './routes/api/ai/ask'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiContextRoute = ApiAiContextRouteImport.update({
  id: '/api/ai/context',
  path: '/api/ai/context',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiAskRoute = ApiAiAskRouteImport.update({
  id: '/api/ai/ask',
  path: '/api/ai/ask',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/ai/ask': typeof ApiAiAskRoute
  '/api/ai/context': typeof ApiAiContextRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/ai/ask': typeof ApiAiAskRoute
  '/api/ai/context': typeof ApiAiContextRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/ai/ask': typeof ApiAiAskRoute
  '/api/ai/context': typeof ApiAiContextRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/ai/ask' | '/api/ai/context'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/ai/ask' | '/api/ai/context'
  id: '__root__' | '/' | '/api/ai/ask' | '/api/ai/context'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiAiAskRoute: typeof ApiAiAskRoute
  ApiAiContextRoute: typeof ApiAiContextRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/context': {
      id: '/api/ai/context'
      path: '/api/ai/context'
      fullPath: '/api/ai/context'
      preLoaderRoute: typeof ApiAiContextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/ask': {
      id: '/api/ai/ask'
      path: '/api/ai/ask'
      fullPath: '/api/ai/ask'
      preLoaderRoute: typeof ApiAiAskRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiAiAskRoute: ApiAiAskRoute,
  ApiAiContextRoute: ApiAiContextRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
