/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoCalldataParseRouteImport } from './routes/demo/calldata-parse'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoCalldataParseRoute = DemoCalldataParseRouteImport.update({
  id: '/demo/calldata-parse',
  path: '/demo/calldata-parse',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo/calldata-parse': typeof DemoCalldataParseRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo/calldata-parse': typeof DemoCalldataParseRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/demo/calldata-parse': typeof DemoCalldataParseRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/demo/calldata-parse'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/demo/calldata-parse'
  id: '__root__' | '/' | '/demo/calldata-parse'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemoCalldataParseRoute: typeof DemoCalldataParseRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/calldata-parse': {
      id: '/demo/calldata-parse'
      path: '/demo/calldata-parse'
      fullPath: '/demo/calldata-parse'
      preLoaderRoute: typeof DemoCalldataParseRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemoCalldataParseRoute: DemoCalldataParseRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
